# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: data/creative_ad
dataset_configs:
- all
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
reward_funcs: ["format", "answer_quality", "think_quality"]
beta: 0.01
bf16: true
temperature: 0.98
use_vllm: false  # true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
do_eval: true
eval_strategy: steps
eval_steps: 2000
gradient_accumulation_steps: 8
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1e-06
log_level: info
logging_steps: 2
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 512
max_steps: -1
num_generations: 8
num_train_epochs: 2
output_dir: Qwen2.5-1.5B-Open-R1-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- wandb
save_strategy: epoch
seed: 42
warmup_ratio: 0.1